#pragma once

#include <juce_core/juce_core.h>
#include <juce_audio_basics/juce_audio_basics.h>
#include "Sha1.h"
#include "BridgeScript.h"

#include <atomic>
#include <vector>
#include <mutex>
#include <memory>

namespace WebBridge
{

class WebBridgeServer : public juce::Thread
{
public:
    WebBridgeServer(int preferredPort = 8766)
        : juce::Thread("WebBridgeServerThread"),
          activePort(preferredPort),
          audioFifo(ringBufferSize),
          audioRingBuffer(2, ringBufferSize)
    {
        audioRingBuffer.clear();
        getOfflineDirectory().createDirectory();
    }

    ~WebBridgeServer() override
    {
        stopServer();
    }

    void startServer()
    {
        if (isThreadRunning())
            return;

        shouldStop = false;
        startThread(juce::Thread::Priority::high);
    }

    void stopServer()
    {
        shouldStop = true;
        signalThreadShouldExit();

        if (serverSocket != nullptr)
            serverSocket->close();

        if (clientSocket != nullptr)
            clientSocket->close();

        stopThread(2000);
    }

    int getPort() const noexcept { return activePort.load(); }
    bool isClientConnected() const noexcept { return clientConnected.load(); }

    static juce::File getOfflineDirectory()
    {
        return juce::File::getSpecialLocation(juce::File::userHomeDirectory)
                   .getChildFile(".local/share/BrowserInstrument/offline");
    }

    juce::StringArray getOfflinePresets()
    {
        juce::StringArray presets;
        auto dir = getOfflineDirectory();
        if (dir.isDirectory())
        {
            auto subdirs = dir.findChildFiles(juce::File::findDirectories, false);
            for (const auto& d : subdirs)
            {
                presets.add(d.getFileName());
            }
        }
        return presets;
    }

    // Audio Output: Read audio generated by browser (called from processBlock)
    int readAudioFromBrowser(float* const* destinationChannels, int numChannels, int numSamples)
    {
        int available = audioFifo.getNumReady();
        int samplesToRead = juce::jmin(available, numSamples);

        if (samplesToRead <= 0)
            return 0;

        int start1, size1, start2, size2;
        audioFifo.prepareToRead(samplesToRead, start1, size1, start2, size2);

        for (int ch = 0; ch < numChannels; ++ch)
        {
            const int sourceCh = juce::jmin(ch, audioRingBuffer.getNumChannels() - 1);
            if (size1 > 0)
                juce::FloatVectorOperations::copy(destinationChannels[ch],
                                                   audioRingBuffer.getReadPointer(sourceCh, start1),
                                                   size1);
            if (size2 > 0)
                juce::FloatVectorOperations::copy(destinationChannels[ch] + size1,
                                                   audioRingBuffer.getReadPointer(sourceCh, start2),
                                                   size2);
        }

        audioFifo.finishedRead(size1 + size2);
        return samplesToRead;
    }

    // Audio Input: Send DAW audio to browser (called from processBlock)
    void sendAudioToBrowser(const float* const* sourceChannels, int numChannels, int numSamples)
    {
        if (!clientConnected.load() || numSamples <= 0 || sourceChannels == nullptr)
            return;

        const int chs = juce::jmin(numChannels, 2);
        const int payloadSize = 4 + numSamples * chs * sizeof(float);
        std::vector<uint8_t> packet(payloadSize);

        packet[0] = 0x01; // Audio input packet
        packet[1] = static_cast<uint8_t>(chs);
        packet[2] = static_cast<uint8_t>(numSamples & 0xFF);
        packet[3] = static_cast<uint8_t>((numSamples >> 8) & 0xFF);

        float* f32 = reinterpret_cast<float*>(packet.data() + 4);
        if (chs == 1)
        {
            for (int i = 0; i < numSamples; ++i)
                f32[i] = sourceChannels[0][i];
        }
        else
        {
            for (int i = 0; i < numSamples; ++i)
            {
                f32[i * 2 + 0] = sourceChannels[0][i];
                f32[i * 2 + 1] = sourceChannels[1][i];
            }
        }

        sendWebSocketBinary(packet.data(), packet.size());
    }

    // MIDI: Send DAW MIDI to browser
    void sendMidiToBrowser(const juce::MidiMessage& msg)
    {
        if (!clientConnected.load() || msg.getRawDataSize() < 1)
            return;

        const uint8_t* raw = msg.getRawData();
        const int size = msg.getRawDataSize();

        std::vector<uint8_t> packet(1 + size);
        packet[0] = 0x02; // MIDI packet
        std::memcpy(packet.data() + 1, raw, size);

        sendWebSocketBinary(packet.data(), packet.size());
        midiOutActivity.store(true);
    }

    // MIDI: Read MIDI received from browser (called from processBlock)
    void getMidiFromBrowser(juce::MidiBuffer& destinationBuffer, int sampleOffset = 0)
    {
        std::lock_guard<std::mutex> lock(midiMutex);
        for (const auto& msg : incomingMidi)
        {
            destinationBuffer.addEvent(msg, sampleOffset);
        }
        if (!incomingMidi.empty())
        {
            midiInActivity.store(true);
            incomingMidi.clear();
        }
    }

    // Telemetry flags
    bool checkAndResetMidiInActivity() { return midiInActivity.exchange(false); }
    bool checkAndResetMidiOutActivity() { return midiOutActivity.exchange(false); }
    float getPeakAudioOutLevel() { return peakAudioOut.exchange(0.0f); }

private:
    void run() override
    {
        while (!threadShouldExit() && !shouldStop)
        {
            serverSocket = std::make_unique<juce::StreamingSocket>();
            int port = activePort.load();
            bool bound = false;

            for (int attempt = 0; attempt < 25; ++attempt)
            {
                if (serverSocket->createListener(port, "127.0.0.1"))
                {
                    activePort.store(port);
                    bound = true;
                    break;
                }
                port++;
            }

            if (!bound)
            {
                wait(2000);
                continue;
            }

            while (!threadShouldExit() && !shouldStop)
            {
                auto* client = serverSocket->waitForNextConnection();
                if (client == nullptr)
                {
                    wait(30);
                    continue;
                }

                handleClientConnection(client);
            }
        }
    }

    void handleClientConnection(juce::StreamingSocket* client)
    {
        std::unique_ptr<juce::StreamingSocket> sock(client);
        char buffer[2048];
        juce::String request;

        const auto startTime = juce::Time::getCurrentTime();
        while ((juce::Time::getCurrentTime() - startTime).inMilliseconds() < 3000)
        {
            int bytesRead = sock->read(buffer, sizeof(buffer) - 1, false);
            if (bytesRead > 0)
            {
                buffer[bytesRead] = 0;
                request += juce::String::fromUTF8(buffer, bytesRead);
                if (request.contains("\r\n\r\n"))
                    break;
            }
            else
            {
                wait(10);
            }
        }

        if (request.isEmpty())
            return;

        // Check if WebSocket upgrade
        if (request.containsIgnoreCase("Upgrade: websocket"))
        {
            if (handleWebSocketUpgrade(*sock, request))
            {
                clientSocket.reset(sock.release());
                clientConnected.store(true);
                processWebSocketFrames(*clientSocket);
                clientConnected.store(false);
                clientSocket.reset();
            }
        }
        else
        {
            // Standard HTTP GET request for offline localhost files!
            handleHttpStaticFile(*sock, request);
        }
    }

    bool handleWebSocketUpgrade(juce::StreamingSocket& socket, const juce::String& request)
    {
        juce::String secKey;
        const auto lines = juce::StringArray::fromLines(request);
        for (const auto& line : lines)
        {
            if (line.startsWithIgnoreCase("Sec-WebSocket-Key:"))
            {
                secKey = line.fromFirstOccurrenceOf(":", false, false).trim();
                break;
            }
        }

        if (secKey.isEmpty())
            return false;

        juce::String concat = secKey + "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
        auto shaDigest = Sha1::compute(concat.toStdString());
        juce::String acceptKey = juce::Base64::toBase64(shaDigest.data(), shaDigest.size());

        juce::String response = "HTTP/1.1 101 Switching Protocols\r\n"
                                "Upgrade: websocket\r\n"
                                "Connection: Upgrade\r\n"
                                "Sec-WebSocket-Accept: " + acceptKey + "\r\n\r\n";

        auto utf8 = response.toRawUTF8();
        return socket.write(utf8, (int)std::strlen(utf8)) > 0;
    }

    void handleHttpStaticFile(juce::StreamingSocket& socket, const juce::String& request)
    {
        // Extract requested path e.g. "GET /offline/ypc2000/index.html HTTP/1.1"
        juce::String firstLine = request.upToFirstOccurrenceOf("\r\n", false, false);
        auto tokens = juce::StringArray::fromTokens(firstLine, " ", "");
        if (tokens.size() < 2 || (tokens[0] != "GET" && tokens[0] != "HEAD"))
        {
            sendHttpResponse(socket, 400, "Bad Request", "text/plain", "Bad Request");
            return;
        }

        bool isHead = (tokens[0] == "HEAD");

        juce::String path = tokens[1].upToFirstOccurrenceOf("?", false, false);

        if (path == "/bridge.js" || path == "bridge.js")
        {
            juce::String js = getInjectionScript(activePort.load());
            sendHttpResponse(socket, 200, "OK", "application/javascript; charset=utf-8", js);
            return;
        }

        if (path == "/" || path == "/index.html")
        {
            juce::String bookmarklet = "javascript:(function(){const s=document.createElement('script');s.src='http://127.0.0.1:"
                                     + juce::String(activePort.load()) + "/bridge.js?t='+Date.now();document.head.appendChild(s);})();";

            juce::String html = R"HTML(<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>BrowserInstrument Bridge</title>
<style>
body { background: #0f1117; color: #e2e8f0; font-family: -apple-system, BlinkMacSystemFont, sans-serif; display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 90vh; }
.card { background: #1a1d27; border: 1px solid #2d3345; border-radius: 12px; padding: 32px; max-width: 540px; text-align: center; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }
h1 { color: #818cf8; margin-bottom: 8px; }
p { color: #94a3b8; font-size: 14px; line-height: 1.6; }
.btn { display: inline-block; background: #4f46e5; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: bold; margin: 16px 0; border: 2px dashed #818cf8; cursor: move; }
.btn:hover { background: #4338ca; }
.tip { background: #13151f; padding: 12px; border-radius: 6px; font-size: 12px; color: #38bdf8; }
</style>
</head>
<body>
<div class="card">
  <h1>BrowserInstrument VST3</h1>
  <p>Local Web Audio & MIDI Bridge is active on port <strong>)HTML" + juce::String(activePort.load()) + R"HTML(</strong></p>
  <p>Trascina questo pulsante nella barra dei segnalibri di Chrome / Firefox per connettere qualsiasi tab o finestra alla DAW con 1 click:</p>
  <a class="btn" href=")HTML" + bookmarklet + R"HTML(">▶ Connetti Tab a Bitwig</a>
  <div class="tip">Suggerimento: Apri YPC2000, YouTube o qualsiasi Web Synth in una tab, poi clicca sul segnalibro!</div>
</div>
</body>
</html>)HTML";

            sendHttpResponse(socket, 200, "OK", "text/html; charset=utf-8", html);
            return;
        }

        if (path.startsWith("/offline/"))
            path = path.substring(9);
        else if (path.startsWith("/"))
            path = path.substring(1);

        juce::File targetFile = getOfflineDirectory().getChildFile(path);
        if (targetFile.isDirectory())
            targetFile = targetFile.getChildFile("index.html");

        if (!targetFile.existsAsFile())
        {
            juce::String notFound = "<html><body><h2>404 Not Found</h2><p>Offline instrument not found: " + path + "</p></body></html>";
            sendHttpResponse(socket, 404, "Not Found", "text/html", notFound);
            return;
        }

        juce::MemoryBlock fileData;
        if (!targetFile.loadFileAsData(fileData))
        {
            sendHttpResponse(socket, 500, "Error", "text/plain", "Failed to read file");
            return;
        }

        juce::String mime = getMimeType(targetFile.getFileExtension());
        sendHttpResponse(socket, 200, "OK", mime, fileData.getData(), fileData.getSize());
    }

    static juce::String getMimeType(const juce::String& ext)
    {
        auto e = ext.toLowerCase();
        if (e == ".html" || e == ".htm") return "text/html; charset=utf-8";
        if (e == ".js" || e == ".mjs")   return "application/javascript; charset=utf-8";
        if (e == ".css")                 return "text/css; charset=utf-8";
        if (e == ".json")                return "application/json";
        if (e == ".png")                 return "image/png";
        if (e == ".jpg" || e == ".jpeg") return "image/jpeg";
        if (e == ".svg")                 return "image/svg+xml";
        if (e == ".wasm")                return "application/wasm";
        if (e == ".wav")                 return "audio/wav";
        if (e == ".mp3")                 return "audio/mpeg";
        return "application/octet-stream";
    }

    void sendHttpResponse(juce::StreamingSocket& socket, int statusCode, const juce::String& statusText,
                          const juce::String& contentType, const void* data, size_t size)
    {
        juce::String header = "HTTP/1.1 " + juce::String(statusCode) + " " + statusText + "\r\n"
                              "Content-Type: " + contentType + "\r\n"
                              "Content-Length: " + juce::String(size) + "\r\n"
                              "Access-Control-Allow-Origin: *\r\n"
                              "Connection: close\r\n\r\n";

        auto utf8 = header.toRawUTF8();
        socket.write(utf8, (int)std::strlen(utf8));
        if (size > 0 && data != nullptr)
            socket.write(data, (int)size);
    }

    void sendHttpResponse(juce::StreamingSocket& socket, int statusCode, const juce::String& statusText,
                          const juce::String& contentType, const juce::String& textBody)
    {
        auto utf8Body = textBody.toRawUTF8();
        sendHttpResponse(socket, statusCode, statusText, contentType, utf8Body, std::strlen(utf8Body));
    }

    void processWebSocketFrames(juce::StreamingSocket& socket)
    {
        std::vector<uint8_t> frameBuffer;

        while (!threadShouldExit() && !shouldStop && socket.isConnected())
        {
            uint8_t header[2];
            int r = socket.read(header, 2, true);
            if (r != 2)
                break;

            const uint8_t b0 = header[0];
            const uint8_t b1 = header[1];

            const uint8_t opcode = b0 & 0x0F;
            const bool isMasked = (b1 & 0x80) != 0;
            uint64_t payloadLen = b1 & 0x7F;

            if (opcode == 0x08) // Close
                break;

            if (payloadLen == 126)
            {
                uint8_t ext[2];
                if (socket.read(ext, 2, true) != 2) break;
                payloadLen = (static_cast<uint64_t>(ext[0]) << 8) | ext[1];
            }
            else if (payloadLen == 127)
            {
                uint8_t ext[8];
                if (socket.read(ext, 8, true) != 8) break;
                payloadLen = 0;
                for (int i = 0; i < 8; ++i)
                    payloadLen = (payloadLen << 8) | ext[i];
            }

            uint8_t mask[4] = { 0, 0, 0, 0 };
            if (isMasked)
            {
                if (socket.read(mask, 4, true) != 4) break;
            }

            frameBuffer.resize(payloadLen);
            size_t bytesRead = 0;
            while (bytesRead < payloadLen)
            {
                int chunk = socket.read(frameBuffer.data() + bytesRead,
                                        static_cast<int>(payloadLen - bytesRead),
                                        false);
                if (chunk <= 0) break;
                bytesRead += chunk;
            }
            if (bytesRead != payloadLen) break;

            if (isMasked)
            {
                for (size_t i = 0; i < payloadLen; ++i)
                    frameBuffer[i] ^= mask[i % 4];
            }

            if (opcode == 0x09) // Ping
            {
                sendWebSocketFrame(0x0A, frameBuffer.data(), frameBuffer.size()); // Pong
                continue;
            }

            if (opcode == 0x02) // Binary frame
            {
                handleIncomingBinaryPayload(frameBuffer.data(), frameBuffer.size());
            }
        }
    }

    void handleIncomingBinaryPayload(const uint8_t* data, size_t size)
    {
        if (size < 1) return;

        const uint8_t packetType = data[0];

        if (packetType == 0x01 && size >= 4)
        {
            // Audio Output from Browser: [0x01, numChannels, lenLo, lenHi, ...float32]
            const int chs = data[1];
            const int sampleCount = data[2] | (data[3] << 8);
            const size_t expectedBytes = 4 + sampleCount * chs * sizeof(float);

            if (size >= expectedBytes && chs > 0 && sampleCount > 0)
            {
                const float* f32 = reinterpret_cast<const float*>(data + 4);
                writeAudioToFifo(f32, chs, sampleCount);
            }
        }
        else if (packetType == 0x02 && size >= 4)
        {
            // MIDI from Browser: [0x02, status, data1, data2]
            const uint8_t status = data[1];
            const uint8_t d1 = data[2];
            const uint8_t d2 = data[3];

            juce::MidiMessage msg(status, d1, d2);
            std::lock_guard<std::mutex> lock(midiMutex);
            incomingMidi.push_back(msg);
            midiInActivity.store(true);
        }
    }

    void writeAudioToFifo(const float* interleavedData, int numChannels, int numSamples)
    {
        int freeSpace = audioFifo.getFreeSpace();
        if (freeSpace < numSamples)
        {
            int toDiscard = numSamples - freeSpace;
            audioFifo.finishedRead(toDiscard);
        }

        int start1, size1, start2, size2;
        audioFifo.prepareToWrite(numSamples, start1, size1, start2, size2);

        float maxPeak = 0.0f;

        for (int i = 0; i < size1; ++i)
        {
            float s0 = interleavedData[i * numChannels + 0];
            float s1 = numChannels > 1 ? interleavedData[i * numChannels + 1] : s0;
            audioRingBuffer.setSample(0, start1 + i, s0);
            audioRingBuffer.setSample(1, start1 + i, s1);
            maxPeak = juce::jmax(maxPeak, std::abs(s0), std::abs(s1));
        }

        for (int i = 0; i < size2; ++i)
        {
            int srcIdx = (size1 + i) * numChannels;
            float s0 = interleavedData[srcIdx + 0];
            float s1 = numChannels > 1 ? interleavedData[srcIdx + 1] : s0;
            audioRingBuffer.setSample(0, start2 + i, s0);
            audioRingBuffer.setSample(1, start2 + i, s1);
            maxPeak = juce::jmax(maxPeak, std::abs(s0), std::abs(s1));
        }

        audioFifo.finishedWrite(size1 + size2);

        float currentPeak = peakAudioOut.load();
        if (maxPeak > currentPeak)
            peakAudioOut.store(maxPeak);
    }

    void sendWebSocketBinary(const uint8_t* data, size_t size)
    {
        sendWebSocketFrame(0x02, data, size);
    }

    void sendWebSocketFrame(uint8_t opcode, const uint8_t* payload, size_t payloadLen)
    {
        std::lock_guard<std::mutex> lock(socketWriteMutex);
        if (clientSocket == nullptr || !clientSocket->isConnected())
            return;

        std::vector<uint8_t> frame;
        frame.reserve(10 + payloadLen);

        frame.push_back(0x80 | (opcode & 0x0F));

        if (payloadLen <= 125)
        {
            frame.push_back(static_cast<uint8_t>(payloadLen));
        }
        else if (payloadLen <= 65535)
        {
            frame.push_back(126);
            frame.push_back(static_cast<uint8_t>((payloadLen >> 8) & 0xFF));
            frame.push_back(static_cast<uint8_t>(payloadLen & 0xFF));
        }
        else
        {
            frame.push_back(127);
            for (int i = 7; i >= 0; --i)
                frame.push_back(static_cast<uint8_t>((payloadLen >> (i * 8)) & 0xFF));
        }

        if (payloadLen > 0 && payload != nullptr)
        {
            frame.insert(frame.end(), payload, payload + payloadLen);
        }

        clientSocket->write(frame.data(), static_cast<int>(frame.size()));
    }

    static constexpr int ringBufferSize = 65536;

    std::atomic<bool> shouldStop { false };
    std::atomic<int> activePort { 8765 };
    std::atomic<bool> clientConnected { false };
    std::atomic<bool> midiInActivity { false };
    std::atomic<bool> midiOutActivity { false };
    std::atomic<float> peakAudioOut { 0.0f };

    std::unique_ptr<juce::StreamingSocket> serverSocket;
    std::unique_ptr<juce::StreamingSocket> clientSocket;
    std::mutex socketWriteMutex;

    juce::AbstractFifo audioFifo;
    juce::AudioBuffer<float> audioRingBuffer;

    std::mutex midiMutex;
    std::vector<juce::MidiMessage> incomingMidi;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(WebBridgeServer)
};

} // namespace WebBridge
